### ISSUE TITLE
Create REST routes on server for all required features.

### ISSUE THREAD

**Issue by urosjarc** [Danilo-Danijel-team/sms_sender#10]
Create all REST routes so that every feature flow can be implemented with them.
 - [ ] Collaborate with @ethernal12 so that you get postman tests beforehand for easy development,
so that you can check if responses meet the requirements of the application.
 - [ ] Remember @ethernal12 that he should start doing #11 

Some of the needed routes that I take from top of my head are:
 - [x] POST **/auth/local** - Send password
 - [x] GET **/auth/user** - Is user authenticated
 - [x] GET **/google/calendar** - Get calendar events
 - [x] POST **/msg** - Send msg manualy
 - [x] GET **/msg** - Get msg history
 - [x] GET **/msg/:id** - Get specific msg details from history
 - [x] GET **/settings** - Get all settings
 - [x] PUT **/settings/:id** - Update specific setting
 - [x] GET **/history** - Get action history
 - [x] GET **/contacts** - Get all contacts from phone book
 - [x] POST **/contact** - Create new contact
 - [x] PUT **/contact/:id** - Update specific contact
 - [x] DELETE **/contact/:id** - Delete specific contact
 - [x] GET **/contacts/:id** - Get specific contact
 - [x] GET **/contacts/export** - Export all contacts
 - [x] POST **/contacts/import** - Import contacts

Also take care that:

- [ ] Create error responses are in standard format like so..

```json
{ "error": {...} }
```

So that on frontend you can easily check if there is error in response like so:

```js 
(res) => {
  if("error" in res) ...
}
```

**Comment by danilojezernik** [comment]
@urosjarc @ethernal12 : Sem se igral z Upload path in naredil naslednje:

`  // TODO: Delete if/else statement on upload to server and use uploadPath in else statement
  if (process.env.PORT === '3000') {
    uploadPath = path.join(__dirname, '../public/') + sampleFile.name;
  } else {
    uploadPath = `${req.protocol}://${req.hostname}/${sampleFile.name}`;
  }`

Za voljo testiranja bo ob izbiri protocola 3000 izbralo pot na disku. Ko bo enkrat na strani bo izbralo zahtevan protocol, hostname in bo uploadalo na '/'.

Kaj praviš Uroš?

**Comment by urosjarc** [comment]
@danilojezernik Zgleda ok, a se v hostname skriva tudi port... Si preveril?

**Comment by danilojezernik** [comment]
@urosjarc Port se v hostname ne nahaja. Ubistvu koda z portu zgleda tako:

`uploadPath = `${req.protocol}://${req.hostname}:${process.env.PORT}/${sampleFile.name}`;`

Do porta se dostopa preko `.env`.

**Comment by danilojezernik** [comment]
@urosjarc @ethernal12  - Uroš, kako naj standardiziram (da bi na redil funkcijo v utils in jo exportal) error v .catch((err)) => res.status(404).send(err);? Sm že probu vsega boga...

**Comment by urosjarc** [comment]
@danilojezernik: Težko vidim kaj hočeš pravzaprav doseči, mi lahko posreduješ malce več kode in pojasnila.

**Comment by danilojezernik** [comment]
@urosjarc : Se opravičujem za pozen odgovor.  Gre se za to, da bi uporabil eno funkcijo za vse response v catch-ih. Kot se za to uporablja funkcija v utils errorThrow. Lahko v nedeljo pogledamo, pa še zaključimo in mergamo :)

**Comment by urosjarc** [comment]
@danilojezernik Ja najbolje da pogledamo v nedeljo, bo veliko bolje kot preko sms/ov
